DROP TABLE IF EXISTS TB_GENDER;
DROP TABLE IF EXISTS TB_PERSON;

CREATE TABLE TB_PERSON (
  ID_PERSON INTEGER AUTO_INCREMENT PRIMARY KEY,
  FULL_NAME VARCHAR(50) NOT NULL,
  BIRTHDATE DATE NULL,
  GENDER_ID INTEGER NOT NULL
);

CREATE TABLE TB_GENDER (
  ID_GENDER INTEGER AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(10) NOT NULL
);

ALTER table TB_PERSON
ADD CONSTRAINT FK_GENDER_PERSON
FOREIGN KEY (GENDER_ID)
REFERENCES TB_GENDER (ID_GENDER);